# Generated by Django 5.1.4 on 2025-02-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='tasks_asset'),
        ),
    ]
